### ISSUE TITLE
Add .NET 8 support

### ISSUE THREAD

**Issue by mrmartan** [benmccallum/dotnet-fix-references#12]
Add .NET 8 support

**Comment by mrmartan** [comment]
#11

**Comment by Jack-Edwards** [comment]
Any updates on whether this project will support .NET 8.0?

**Comment by benmccallum** [comment]
Sorry all, just merged the PR. Apologies, I'd been on holidays and intentionally wasn't looking at my computer :) Should support net8 momentarily :)
