### ISSUE TITLE
Mixed backslash and forward slash issue

### ISSUE THREAD

**Issue by marcanpilami** [benmccallum/dotnet-fix-references#4]
Hi. Thanks for this tool! I use it for the docker restore issue.

I have encountered a small issue on a big windows-developed project compiled on Linux machines.

On https://github.com/benmccallum/dotnet-references/blob/112de6d5ada3b5415d6c3e0f84cd6dd6a16673ba/src/dotnet-references/Common.cs#L24 

You use the windows separator instead of `Path.DirectorySeparatorChar`. So whenever we have linux-style separators, we get a `Could not find csproj file path for: 'Include="../xxxProject/xxxProject.csproj'.` error.

However, as many projects actually a happy mix of forward and back slashes, I believe the best way to deal with this is to String.Replace all back with forward, as you actually already do in FixLocationsOfProjectsProcessor.cs. 

Thanks for your help!

**Comment by marcanpilami** [comment]
I should add that a workaround (works for me (tm)) is to run 
```
RUN find ./ -type f -name '*.csproj' -exec sed -i -e "s|/>|ENDTAG|g" -e "s|</|CLOSINGTAG|g" -e "s|\/|\\\|g" -e "s|ENDTAG|/>|g" -e "s|CLOSINGTAG|</|g" {} \;
```

Ugly, but my sed-fu is quite rusty.

**Comment by benmccallum** [comment]
Thanks @marcanpilami, glad it helps you! I'll sort this out this weekend if I get a sec. I'd spotted the other one like you mention, but missed this! Appreciate your initial debug on this :)

**Comment by benmccallum** [comment]
Potentially I should just whip Path.GetFileName in there instead and let it deal with the xplat fun!

**Comment by benmccallum** [comment]
I think I remember this utility method and its purpose was specifically for references in .sln or .csproj files which for me always seemed to be `\` , and I think I thought that would always be the case given VS probably always writes those into those files, but perhaps that's not the case these days for those using VS for Mac or VS Code.

Anyway, I've used `Path.GetFileName` and tested on Windows, will be able to test on Linux a bit later on my own stuff too. Let me know how that goes and if it's still an issue, shout out!

**Comment by benmccallum** [comment]
FYI, fixed in 0.0.5.

**Comment by benmccallum** [comment]
Damn, having issues now because that bit of code must have been dealing with inputs like:
`, "MyProject\MyProject.csproj"` (from the SolutionFile search regex) and a standard path like from the Project file. , hence the dodgy LastIndexOf and substring stuff... Should've taken your initial suggestion :P

I'm not super happy with how this works, the regex is a bit nasty, but I should be using a matching group there to get the file path without the wrapping rubbish I don't need. Bit stretched for time at the moment though, so that'll have to wait for another day.

**Comment by benmccallum** [comment]
Try 0.0.6 and let me know how you go.

**Comment by benmccallum** [comment]
Going to close this as I put in the fix and haven't heard back. Do let me know if you have any issues on the latest version though.

**Comment by marcanpilami** [comment]
Sorry for the wait - yep it works great! Thanks a lot.
