### ISSUE TITLE
Support .NET 5.0

### ISSUE THREAD

**Issue by espenrl** [benmccallum/dotnet-fix-references#6]
See PR #5

**Comment by benmccallum** [comment]
Amazing, thanks @espenrl !

**Comment by benmccallum** [comment]
@espenrl , should be available via nuget a few minutes, had to sort out the GitHub Action to get it building but it's pushed now. Thanks again.

**Comment by espenrl** [comment]
You're welcome. I've upgraded and it works like a charm on Ubuntu / .NET 5.
